apiVersion: v1
data:
  appsettings.json: |
    {
      "DataSources": {
        "EmissionsDataSource": "ElectricityMaps",
        "Configurations": {
          "ElectricityMaps": {
            "Type": "ElectricityMaps",
            "APITokenHeader": "auth-token",
            "BaseURL": "https://api.electricitymap.org/v3/"
          }
        }
      },
      "LocationDataSourcesConfiguration": {
        "LocationSourceFiles": ["locations.json"]
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*"
    }
  locations.json: |
    {
      "KR": {
        "Latitude": "37.5665",
        "Longitude": "126.9780",
        "Name": "KR"
      },
      "JP-TK": {
        "Latitude": "35.6762",
        "Longitude": "139.6503",
        "Name": "JP-TK"
      },
      "US-MIDA-PJM": {
        "Latitude": "37.3719",
        "Longitude": "-79.8164",
        "Name": "US-MIDA-PJM"
      }
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/part-of: greenops
  name: carbon-aware-sdk-config
  namespace: greenops-infra
